version: "3.4"

services:
  swoole-only:
    container_name: "swoole-only"
    image: ghcr.io/nhzex/php-docker2:4.7-php7.4
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
      - "/tmp/composer:/root/.composer/cache/files:rw"
      - "/tmp/phpstan:/tmp/phpstan:rw"
    working_dir: /imi
    command: tail -f /dev/null