name: Static Code Analysis

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      fail-fast: true
      cache-key: cache-v1
      php-versions: 7.4
      extensions: sockets, curl, hprose, swoole-swoole/swoole-src@v4.6.7
      SWOOLE_CONFIGURE_OPTS: >-
        --enable-openssl
        --enable-http2
        --enable-mysqlnd
        --enable-sockets
        --enable-swoole-curl
        --enable-swoole-json
      SWOOLE_LINUX_LIBS: libcurl4-openssl-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.cache-key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          tools: pecl, composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Version
        run: |
          composer -V
          php -m
          php --ri swoole

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache analyse
        uses: actions/cache@v2
        with:
          path: /tmp/phpstan
          key: phpstan-analyse
          restore-keys: phpstan-analyse

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist --no-progress
          cd split-repository
          composer install --no-interaction --prefer-dist --no-progress

      - name: Analyse
        run: |
          ./vendor/bin/phpstan analyse --memory-limit 1G